apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: test-be
          image: ccr.ccs.tencentyun.com/calabash/test_be_image
          command: ["/entry_point.sh"]
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
