apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: test-fe
          image: ccr.ccs.tencentyun.com/calabash/test_fe_image
          command: ["/entry_point.sh"]
          ports:
            - containerPort: 800
          env:
            # nginx反向代理地址
            - name: BACKEND_URL
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 800
      nodePort: 30007
